export default {
  iconUndo: require('../assets/ic_undo.png'),
  iconClose: require('../assets/ic_close.png'),
  iconHeart: require('../assets/ic_heart.png'),
  iconStar: require('../assets/ic_star.png'),
  iconThunder: require('../assets/ic_thunder.png'),
  iconVolume: require('../assets/ic_volume.png'),
  iconArrowDown: require('../assets/ic_arrow_down.png'),
  imgDuolingo: require('../assets/img_duolingo.png'),
  iconFire: require('../assets/fire.png'),
  iconCompass: require('../assets/compass.png'),
  iconFlash: require('../assets/flash.png'),
  iconRibbon: require('../assets/ribbon.png'),
  iconWater: require('../assets/water.png'),
  imgPizza: require('../assets/pizza.png'),
  imgBeef: require('../assets/beef.png'),
  imgSpaghetti: require('../assets/spaghetti.png'),
  imgFirst: require('../assets/first.png'),
  imgSecond: require('../assets/second.png'),
  imgThird: require('../assets/third.png'),
  imgRedShoe: require('../assets/red_shoe.png'),
  imgYellowShoe: require('../assets/yellow_shoe.png'),
  imgBlueShoe: require('../assets/blue_shoe.png'),
  imgGreenShoe: require('../assets/green_shoe.png'),
  imgShoppingCart: require('../assets/shopping_cart.png'),
};
